
- hosts: localhost
  gather_facts: no
  tasks:

    - name: Create {{ sg }} security group
      os_security_group:
        state: present
        name: "{{ sg }}"
    - name: Allow any ICMP
      os_security_group_rule:
        security_group: "{{ sg }}"
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0

    - name: Allow any TCP connection
      os_security_group_rule:
        security_group: "{{ sg }}"
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0

    - name: Allow any UDP connection
      os_security_group_rule:
        security_group: "{{ sg }}"
        protocol: udp
        remote_ip_prefix: 0.0.0.0/0
