- hosts: localhost
  tasks:
    # - name: Create public network
    #   os_network:
    #     state: present
    #     name: "{{ org }}-public-net"
    #     external: True
    #     shared: True
    #     provider_network_type: vlan
    #     provider_physical_network: datacentre
    #     provider_segmentation_id: 3709
    # - name: Create public subnet
    #   os_subnet:
    #     state: present
    #     network_name: "{{ org }}-public-net"
    #     name: "{{ org }}-public-subnet"
    #     ip_version: 4
    #     cidr: 10.37.9.0/24
    #     gateway_ip: 10.37.9.1
    #     enable_dhcp: yes
    #     allocation_pool_start: 10.37.9.41
    #     allocation_pool_end: 10.37.9.229
    #     dns_nameservers:
    #       - 10.11.27.10
    - name: Destroy  router "{{ org }}-router"
      ignore_errors: yes
      os_router:
        state: absent
        name: "demoproject2-router"

    - name: destroy  private networks
      os_network:
        state: absent
        name: "{{ item }}"
      with_items:
        - web-private-net
        - database-private-net
