
- hosts: localhost
  gather_facts: no
  tasks:

    - name: "Create flavors"
      os_nova_flavor: state={{ item.state }} name={{ item.name }} ram={{ item.ram }} vcpus={{ item.vcpus }} disk={{ item.disk }} ephemeral={{ item.ephemeral }} flavorid={{ item.flavorid }}
      with_items:
        - { state: 'present', name: 'm2.small' , ram: '2048' , vcpus: '1' , disk: '10' , ephemeral: '1' , flavorid: '1' }
        - { state: 'present', name: 'm2.fat' , ram: '51200' , vcpus: '16' , disk: '0' , ephemeral: '15' , flavorid: '2' }
        - { state: 'present', name: 'm2.medium' , ram: '1024' , vcpus: '4' , disk: '0' , ephemeral: '5' , flavorid: '3' }
        - { state: 'present', name: 'm2.large' , ram: '2048' , vcpus: '8' , disk: '0' , ephemeral: '5' , flavorid: '4' }
        - { state: 'present', name: 'm2.master' , ram: '16384' , vcpus: '4' , disk: '45' , ephemeral: '0' , flavorid: '5' }
        - { state: 'present', name: 'm2.node' , ram: '32000' , vcpus: '4' , disk: '20' , ephemeral: '0' , flavorid: '6' }
    - name: Create allowall security group
      os_security_group:
        state: present
        name: allowall
    - name: Allow any ICMP
      os_security_group_rule:
        security_group: allowall
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0
    - name: Allow any SSH connection
      os_security_group_rule:
        security_group: allowall
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
    - name: Create keypair
      os_keypair:
          state: present
          name: "{{keyname}}"
          public_key_file: "{{ '~' | expanduser }}/.ssh/authorized_keys"
